include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - lib/l10n/generated/**

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    require_trailing_commas: false
